name: uncertainty-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit>=1.36
      - pandas>=2.2
      - numpy>=1.26
      - matplotlib>=3.8
      - pytest>=8
